apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-htpasswd
spec:
  version: {{ .TagName }}
  homepage: https://github.com/shibumi/kubectl-htpasswd
  shortDescription: Create nginx-ingress compatible basic-auth secrets
  description: |
    This plugin provides a convenient way to create nginx-ingress compatible
    basic auth secrets.
  caveats: ""
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/shibumi/kubectl-htpasswd/releases/download/{{ .TagName }}/kubectl-htpasswd_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-htpasswd
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/shibumi/kubectl-htpasswd/releases/download/{{ .TagName }}/kubectl-htpasswd_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
      bin: kubectl-htpasswd
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/shibumi/kubectl-htpasswd/releases/download/{{ .TagName }}/kubectl-htpasswd_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
      bin: kubectl-htpasswd
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/shibumi/kubectl-htpasswd/releases/download/{{ .TagName }}/kubectl-htpasswd_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
      bin: kubectl-tree.exe